# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name=b'Sobrenome')),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(null=True, verbose_name=b'Data de nascimento')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name=b'Sobrenome')),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name=b'Sobrenome')),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respons\xe1vel',
                'verbose_name_plural': 'Respons\xe1veis',
            },
        ),
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'verbose_name': 'Ano Letivo', 'verbose_name_plural': 'Anos Letivos'},
        ),
        migrations.AlterField(
            model_name='anoletivo',
            name='data_criacao',
            field=models.DateField(auto_now=True, verbose_name=b'Data de cria\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='anoletivo',
            name='titulo',
            field=models.CharField(max_length=15, unique=True, verbose_name=b'Ano Letivo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='core.Responsavel', verbose_name=b'Respons\xc3\xa1vel'),
        ),
    ]
