# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160611_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 1')),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 2')),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 3')),
                ('nota4', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 4')),
                ('nota5', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 5')),
                ('nota6', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 6')),
                ('nota7', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 7')),
                ('nota8', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Nota 8')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
    ]
