# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160612_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 1'),
        ),
    ]
