# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160612_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 2'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 3'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 4'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 5'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 6'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 7'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota 8'),
        ),
    ]
