# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160612_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name=b'Data')),
                ('texto', models.TextField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.Responsavel', verbose_name='Respons\xe1vel'),
        ),
    ]
